=== rambaut/santa-sim/trunk/examples/santa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="santa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="replicates"/>
				<xs:element ref="simulation"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="replicates" type="xs:integer"/>
	<xs:element name="simulation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="generationCount"/>
				<xs:element ref="genome"/>
				<xs:element ref="population"/>
				<xs:element ref="fitnessFunction"/>
				<xs:element ref="mutator"/>
				<xs:element ref="replicator"/>
				<xs:element minOccurs="0" ref="selector"/>
				<xs:element ref="samplingSchedule"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="generationCount" type="xs:integer"/>
	<xs:element name="genome">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="length"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="length" type="xs:integer"/>
	<xs:element name="population">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="populationSize"/>
				<xs:element ref="inoculum"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="populationSize" type="xs:integer"/>
	<xs:element name="inoculum">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sequence"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sequence">
		<xs:complexType mixed="true">
			<xs:attribute name="label" use="required" type="xs:NCName"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="fitnessFunction">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="aminoAcids"/>
				<xs:element minOccurs="0" ref="nucleotides"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="aminoAcids">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="sites"/>
				<xs:choice>
					<xs:element ref="ageDependentFitness"/>
					<xs:element ref="empiricalFitness"/>
					<xs:element ref="exposureDependentFitness"/>
					<xs:element ref="fluctuatingFitness"/>
					<xs:element ref="frequencyDependentFitness"/>
					<xs:element ref="purifyingFitness"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sites" type="xs:NMTOKEN"/>
	<xs:element name="ageDependentFitness">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="declineRate"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="declineRate" type="xs:decimal"/>
	<xs:element name="empiricalFitness" type="xs:string"/>
	<xs:element name="exposureDependentFitness">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="penalty"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="penalty" type="xs:decimal"/>
	<xs:element name="fluctuatingFitness">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lambda"/>
				<xs:element ref="strength"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="lambda" type="xs:decimal"/>
	<xs:element name="frequencyDependentFitness">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="shape"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="shape" type="xs:decimal"/>
	<xs:element name="purifyingFitness">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fittest"/>
				<xs:element ref="strength"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fittest" type="xs:string"/>
	<xs:element name="nucleotides">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="neutralFitness"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="neutralFitness">
		<xs:complexType/>
	</xs:element>
	<xs:element name="mutator">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nucleotideMutator"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nucleotideMutator">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="mutationRate"/>
				<xs:element ref="transitionBias"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="mutationRate" type="xs:double"/>
	<xs:element name="transitionBias" type="xs:decimal"/>
	
	<xs:element name="replicator">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="clonalReplicator"/>
				<xs:element ref="recombinantReplicator"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="clonalReplicator">
		<xs:complexType/>
	</xs:element>

	<xs:element name="recombinantReplicator">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dualInfectionProbability"/>
				<xs:element ref="recombinationProbability"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dualInfectionProbability" type="xs:decimal"/>
	<xs:element name="recombinationProbability" type="xs:decimal"/>

	<xs:element name="selector">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="rouletteWheelSelector"/>
				<xs:element ref="discreteRouletteWheelSelector"/>
				<xs:element ref="monteCarloSelector"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="rouletteWheelSelector">
		<xs:complexType/>
	</xs:element>
	<xs:element name="discreteRouletteWheelSelector">
		<xs:complexType/>
	</xs:element>
	<xs:element name="monteCarloSelector">
		<xs:complexType/>
	</xs:element>

	<xs:element name="samplingSchedule">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="sampler"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sampler">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="atFrequency"/>
				<xs:element ref="fileName"/>
				<xs:choice>
					<xs:element ref="alignment"/>
					<xs:element ref="statistics"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="atFrequency" type="xs:integer"/>
	<xs:element name="fileName" type="xs:string"/>
	<xs:element name="alignment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="schedule"/>
				<xs:element ref="format"/>
				<xs:element ref="label"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="schedule" type="xs:string"/>
	<xs:element name="format" type="xs:NCName"/>
	<xs:element name="label" type="xs:string"/>
	<xs:element name="statistics">
		<xs:complexType/>
	</xs:element>
	<xs:element name="strength" type="xs:decimal"/>
</xs:schema>

=== rambaut/santa-sim/trunk/examples/fluctuating.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="santa.xsd">
	<replicates>1</replicates>

	<simulation>
		<generationCount>2001</generationCount>

		<genome>
			<length>1218</length>
		</genome>

		<population>
			<populationSize>100000</populationSize>

			<inoculum>
				<sequence label="wildtype">
					GAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGAGAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGA
				</sequence>
			</inoculum>
		</population>

		<fitnessFunction>
			<aminoAcids>
				<sites>51-203</sites>
				<purifyingFitness>
					<fittest>
						GAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGAGAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGA
					</fittest>
					<strength>0.1</strength>
				</purifyingFitness>
			</aminoAcids>
			<aminoAcids>
				<sites>1-50</sites>
				<fluctuatingFitness>
					<lambda>0.0005</lambda>
					<strength>0.5</strength>
				</fluctuatingFitness>
			</aminoAcids>
		</fitnessFunction>

		<mutator>
			<nucleotideMutator>
				<mutationRate>2.5E-5</mutationRate>
				<transitionBias>2.0</transitionBias>
			</nucleotideMutator>
		</mutator>

		<replicator>
			<clonalReplicator/>
		</replicator>

		<samplingSchedule>
			<sampler>
				<atFrequency>100</atFrequency>
				<fileName>fluctuate_%r.nex</fileName>
				<alignment>
					<schedule>
						1200 10
						1400 10
						1600 10
						1800 10
						2000 10
					</schedule>
					<format>NEXUS</format>
					<label>fluctuate_%g_%s</label>
				</alignment>
			</sampler>
			<sampler>
				<atFrequency>1</atFrequency>
				<fileName>fluctuate_%r.csv</fileName>
				<statistics></statistics>
			</sampler>
		</samplingSchedule>

	</simulation>

</santa>

=== rambaut/santa-sim/trunk/examples/small.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="santa.xsd">
	<replicates>1</replicates>

	<simulation>
		<generationCount>1000</generationCount>

		<genome>
			<length>9</length>
		</genome>

		<population>
			<populationSize>100</populationSize>

			<inoculum>
				<sequence label="virus1gen1000">
					GAAGAAGAG
				</sequence>
			</inoculum>
		</population>

		<fitnessFunction>
			<nucleotides>
				<neutralFitness/>
			</nucleotides>
		</fitnessFunction>

		<mutator>
			<nucleotideMutator>
				<mutationRate>1.0E-4</mutationRate>
				<transitionBias>2.0</transitionBias>
			</nucleotideMutator>
		</mutator>

		<replicator>
			<clonalReplicator/>
		</replicator>

		<samplingSchedule>
			<sampler>
				<atFrequency>100</atFrequency>
				<fileName>trees_%r.nex</fileName>
				<tree>
					<format>NEXUS</format>
					<sampleSize>10</sampleSize>
					<label>tip_%g_%s</label>
				</tree>
			</sampler>
		</samplingSchedule>

	</simulation>

</santa>

=== rambaut/santa-sim/trunk/examples/purifying.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="santa.xsd">

    <replicates>1</replicates>

    <simulation>
        <generationCount>1001</generationCount>

        <genome>
            <length>609</length>
        </genome>

        <population>
            <populationSize>100000</populationSize>

            <inoculum>
                <sequence label="wildtype">
                    GAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGA
                </sequence>
            </inoculum>
        </population>

        <fitnessFunction>
            <aminoAcids>
                <purifyingFitness>
                    <fittest>
                        GAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGA
                    </fittest>
                    <strength>
                        <!--
                                      coeficient ~ puryfication strength
                                      0:    neutral
                                      +inf: completely purifying
                                      -->
                        0.5
                    </strength>
                </purifyingFitness>
            </aminoAcids>
        </fitnessFunction>

        <fitnessFunction>
            <empiricalFitness id="background">
                <aminoAcids>1-201,203-279,281-434</aminoAcids>

                <rank breakTies="random|ordered">
                    <sequences>
                        CCTCAGGTCACTCTTTGGCAACGACCCCTCGTCACAATAAAGATAGGGGGGCAACTAAAGGAAGCTCTATTAGATACAGGAGCAGATGATACAGTATTAGAAGAAATGAGTTTGCCAGGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAAGACAGTATGATCAGATACTCATAGAAATCTGTGGACATAAAGCTATAGGTACAGTATTAGTAGGACCTACACCTGTCAACATAATTGGAAGAAATCTGTTGACTCAGATTGGTTGCACTTTAAATTTTCCCATTAGCCCTATTGAGACTGTACCAGTAAAATTAAAGCCAGGAATGGATGGCCCAAAAGTTAAACAATGGCCATTGACAGAAGAAAAAATAAAAGCATTAGTAGAAATTTGTACAGAGATGGAAAAGGAAGGGAAAATTTCAAAAATTGGGCCTGAAAATCCATACAATACTCCAGTATTTGCCATAAAGAAAAAAGACAGTACTAAATGGAGAAAATTAGTAGATTTCAGAGAACTTAATAAGAGAACTCAAGACTTCTGGGAAGTTCAATTAGGAATACCACATCCCGCAGGGTTAAAAAAGAAAAAATCAGTAACAGTACTGGATGTGGGTGATGCATATTTTTCAGTTCCCTTAGATGAAGACTTCAGGAAGTATACTGCATTTACCATACCTAGTATAAACAATGAGACACCAGGGATTAGATATCAGTACAATGTGCTTCCACAGGGATGGAAAGGATCACCAGCAATATTCCAAAGTAGCATGACAAAAATCTTAGAGCCTTTTAGAAAACAAAATCCAGACATAGTTATCTATCAATACATGGATGATTTGTATGTAGGATCTGACTTAGAAATAGGGCAGCATAGAACAAAAATAGAGGAGCTGAGACAACATCTGTTGAGGTGGGGACTTACCACACCAGACAAAAAACATCAGAAAGAACCTCCATTCCTTTGGATGGGTTATGAACTCCATCCTGATAAATGGACAGTACAGCCTATAGTGCTGCCAGAAAAAGACAGCTGGACTGTCAATGACATACAGAAGTTAGTGGGGAAATTGAATTGGGCAAGTCAGATTTACCCAGGGATTAAAGTAAGGCAATTATGTAAACTCCTTAGAGGAACCAAAGCACTAACAGAAGTAATACCACTAACAGAAGAAGCAGAGCTAGAACTGGCAGAAAACAGAGAGATTCTAAAAGAACCAGTACATGGAGTGTATTATGACCCATCAAAAGACTTAATAGCAGAAATACAGAAGCAGGGGCAAGGC
                    </sequences>
                </rank>
                <fitness>
                    <logistic>
                        <minimumFitness>0.1</minimumFitness>
                        <mostFitCount>4</mostFitCount>
                        <leastFitCount>16</leastFitCount>
                    </logistic>
                    <!--<values>1.0 ... 1.0</values>-->
                </fitness>
            </empiricalFitness>
        </fitnessFunction>

        <mutator>
            <nucleotideMutator>
                <mutationRate>1.0E-4</mutationRate>
                <transitionBias>2.0</transitionBias>
            </nucleotideMutator>
        </mutator>

        <replicator>
            <clonalReplicator/>
        </replicator>

        <selector>
            <rouletteWheelSelector/>
        </selector>

        <samplingSchedule>
            <sampler>
                <atFrequency>100</atFrequency>
                <fileName>purify_%r.nex</fileName>
                <alignment>
                    <schedule>
                        <!-- generation count -->
                        200  10
                        400  10
                        600  10
                        800  10
                        1000  10
                    </schedule>
                    <format>NEXUS</format>
                    <label>purify_%g_%s</label>
                </alignment>
            </sampler>
            <sampler>
                <atFrequency>10</atFrequency>
                <fileName>purifying_%r.csv</fileName>
                <statistics></statistics>
            </sampler>
        </samplingSchedule>

    </simulation>

</santa>

=== rambaut/santa-sim/trunk/examples/frequencydependent.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="santa.xsd">
	<replicates>1</replicates>

	<simulation>
		<genome>
			<length>609</length>
		</genome>

		<population>
			<populationSize>10000</populationSize>

			<inoculum>
				<sequence label="virus1gen1000">
					GAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGA
				</sequence>
			</inoculum>
		</population>

		<fitnessFunction>
			<frequencyDependentFitness>
				<aminoAcids>1-5</aminoAcids>
				<shape>0.5</shape>
			</frequencyDependentFitness>
		</fitnessFunction>

		<mutator>
			<nucleotideMutator>
				<mutationRate>1.0E-4</mutationRate>
				<transitionBias>2.0</transitionBias>
			</nucleotideMutator>
		</mutator>

		<replicator>
			<clonalReplicator/>
		</replicator>

		<selector>
			<rouletteWheelSelector/>
		</selector>

		<epoch>
			<generationCount>1001</generationCount>
		</epoch>

		<samplingSchedule>
			<sampler>
				<atFrequency>100</atFrequency>
				<fileName>frequency_%r.nex</fileName>
				<alignment>
					<schedule>
						<!-- generation count -->
						200  10
						400  10
						600  10
						800  10
						1000  10
					</schedule>
					<format>NEXUS</format>
					<label>neutral_%g_%s</label>
				</alignment>
			</sampler>
			<sampler>
				<atFrequency>10</atFrequency>
				<fileName>frequency_%r.csv</fileName>
				<statistics></statistics>
			</sampler>
		</samplingSchedule>

	</simulation>

</santa>
